name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            package-lock.json
            packages/google-sheets/package-lock.json
            packages/market-data/package-lock.json
            packages/revolut-spending/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install package dependencies
        run: npm run install:packages

      - name: Build all packages
        run: npm run build

      - name: Test all packages
        run: npm test
